name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Generate JaCoCo report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
        run: ./gradlew jacocoTestReport