name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run tests
        run: |
          chmod +x gradlew
          ./gradlew test

  coverage:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run jacoco
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport

      - name: Make artefact test-coverage
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: build/reports/jacoco/test/html

  linter:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run checkstyle
        run: |
          chmod +x gradlew
          ./gradlew check

      - name: Make artefact linter
        uses: actions/upload-artifact@v2
        with:
          name: linter
          path: build/reports/checkstyle